---
title: "Final Project Memo - PSTAT 131"
output: html_document
date: '2022-04-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview of Dataset

The dataset includes information on the sizes of sloths, with each row being a different observed sloth. It contains the claw length, the endangered category for the sloth, what species the sloth is, what subspecies the sloth is, its size, tail length, and weight. In addition, the link to the dataset can be found here: https://www.kaggle.com/datasets/bertiemackie/sloth-species . In this data set, there are 4999 observations and 7 predictors. I will be working with both quantitative and qualitative data for the sloths. 
* Quantitative: Claw length, size, tail length, weight
* Qualitative: Endangered category, species, subspecies


## Overview of Research Questions

For this final project, I am interested in predicting if a sloth is two-toed or three-toed (looking at their species). I am also interested in predicting what sub species a sloth belongs to. My response variables would be the sloth species and subspecies. Sloths can either be two-toed or three-toed, and there are many different subspecies inside each two-toed and three-toed species. I think that my questions will be best answered with a classification approach as I am predicting discrete output variables (two-toed or three-toed and subspecies of a sloth). I believe that the predictors that would be especially useful in predicting if a sloth is two-toed or three-toed and what subspecies a sloth is would most likely be the claw length, size, tail length, and weight of the sloth. Moreover, I believe that the goal of my model would be predictive. In this project, I will be using current data to find patterns and figure out the species and/or subspecies of a sloth based on data such as claw length, size, tail length, and weight. 


## Proposed Project Timeline
* April 14th - Data Loaded 
* April 28th - Beginning EDA 
* May 5th - Beginning Model Building 
* May 12th - Write up results + work on draft of paper 
* May 31st - Final edits 

## Questions/Concerns
I'm not sure if there are any data or anything that I'm missing regarding my data set. Do you think that there could possibly be something else I could look into regarding what else I could predict instead?